pipeline:
  identifier: Build_tradercentric_xml_flattener_1724023645546
  name: Build xml-flattener
  orgIdentifier: default
  projectIdentifier: Netcore_test_build
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github_OAuth_1724023610283
        repoName: tradercentric/xml-flattener
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          caching:
            enabled: true
          cloneCodebase: true
          execution:
            steps:
              - step:
                  identifier: runlinter
                  name: run linter
                  spec:
                    command: |-
                      pip install flake8
                      flake8 .
                  timeout: ""
                  type: Run
              - step:
                  identifier: setupvirtualenvironment
                  name: setup virtual environment
                  spec:
                    command: |-
                      python3 -m venv .venv
                      . .venv/bin/activate
                      python3 -m pip install -r requirements.txt
                      python3 -m pip install -e .
                  timeout: ""
                  type: Run
          platform:
            arch: Amd64
            os: Linux
          runtime:
            spec: {}
            type: Cloud
        type: CI
